name: e2e_ocr_shajib
channels:
  - defaults
dependencies:
  - ca-certificates=2022.3.29
  - certifi=2021.10.8
  - openssl=1.1.1n
  - pip=21.2.2
  - python=3.8.13
  - setuptools=61.2.0
  - sqlite=3.38.2
  - vc=14.2
  - vs2015_runtime=14.27.29016
  - wheel=0.37.1
  - wincertstore=0.2
  - pip:
    - astor==0.8.1
    - babel==2.9.1
    - bce-python-sdk==0.8.64
    - cachetools==5.0.0
    - cfgv==3.3.1
    - charset-normalizer==2.0.12
    - click==8.1.2
    - colorama==0.4.4
    - cssselect==1.1.0
    - cssutils==2.4.0
    - cycler==0.11.0
    - cython==0.29.28
    - decorator==5.1.1
    - distlib==0.3.4
    - easyocr==1.4.2
    - et-xmlfile==1.1.0
    - filelock==3.6.0
    - flake8==4.0.1
    - flask==2.1.1
    - flask-babel==2.0.0
    - fonttools==4.32.0
    - future==0.18.2
    - identify==2.4.12
    - idna==3.3
    - imageio==2.17.0
    - imgaug==0.4.0
    - importlib-metadata==4.11.3
    - itsdangerous==2.1.2
    - jinja2==3.1.1
    - kiwisolver==1.4.2
    - lmdb==1.3.0
    - lxml==4.8.0
    - markupsafe==2.1.1
    - matplotlib==3.5.1
    - mccabe==0.6.1
    - networkx==2.8
    - nodeenv==1.6.0
    - numpy==1.19.3
    - opencv-contrib-python==4.4.0.46
    - opencv-python==4.5.5.64
    - opencv-python-headless==4.5.4.60
    - openpyxl==3.0.9
    - packaging==21.3
    - paddlepaddle==2.2.2
    - pandas==1.4.2
    - pillow==9.1.0
    - platformdirs==2.5.2
    - polygon3==3.0.9.1
    - pre-commit==2.18.1
    - premailer==3.10.0
    - protobuf==3.20.0
    - pyclipper==1.3.0.post2
    - pycodestyle==2.8.0
    - pycryptodome==3.14.1
    - pyflakes==2.4.0
    - pyparsing==3.0.8
    - python-bidi==0.4.2
    - python-dateutil==2.8.2
    - python-levenshtein==0.12.2
    - pytz==2022.1
    - pywavelets==1.3.0
    - pyyaml==6.0
    - requests==2.27.1
    - scikit-image==0.19.2
    - scipy==1.8.0
    - shapely==1.8.1.post1
    - shellcheck-py==0.8.0.4
    - six==1.16.0
    - tifffile==2022.4.8
    - toml==0.10.2
    - torch==1.11.0
    - torchvision==0.12.0
    - tqdm==4.64.0
    - typing-extensions==4.2.0
    - urllib3==1.26.9
    - virtualenv==20.14.1
    - visualdl==2.2.3
    - werkzeug==2.1.1
    - zipp==3.8.0
